using System;
using ENode.Commanding;

namespace ENode.EQueue
{
    /// <summary>Represents a message when a command is executed.
    /// <remarks>
    /// This message not means all the domain events generated by this command are handled,
    /// it just means the command is executed by the command handler on CQRS command side.
    /// If you want to know when all the domain events are handled, you should listen to the DomainEventHandledMessage.
    /// </remarks>
    /// </summary>
    [Serializable]
    public class CommandExecutedMessage
    {
        /// <summary>The unique identifier of the command.
        /// </summary>
        public string CommandId { get; set; }
        /// <summary>The aggregate root created or modified by the command.
        /// </summary>
        public string AggregateRootId { get; set; }
        /// <summary>The associated processId of the command.
        /// </summary>
        public string ProcessId { get; set; }
        /// <summary>The status of the command execution.
        /// </summary>
        public CommandStatus CommandStatus { get; set; }
        /// <summary>The code of the exception type if the command execution has any exception.
        /// </summary>
        public int ExceptionCode { get; set; }
        /// <summary>The error message if the command execution status is failed.
        /// </summary>
        public string ErrorMessage { get; set; }
    }
}
